server:
  port: 7052
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bolt
    username: root
    password: mercury
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update